//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBP_Projekt_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cijena_rada
    {
        public Cijena_rada()
        {
            this.Korisnik = new HashSet<Korisnik>();
        }
    
        public int cijenaID { get; set; }
        public double Redovna { get; set; }
        public double Prekovremena { get; set; }
    
        public virtual ICollection<Korisnik> Korisnik { get; set; }
    }
}
