//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBP_Projekt_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        public Korisnik()
        {
            this.Pocetak_ZavrĹˇetak_rada = new HashSet<Pocetak_ZavrĹˇetak_rada>();
            this.Placa = new HashSet<Placa>();
            this.Radno_vrijeme = new HashSet<Radno_vrijeme>();
        }
    
        public int korisnikID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Kor_ime { get; set; }
        public System.DateTime Datum_rodenja { get; set; }
        public string OIB { get; set; }
        public string Lozinka { get; set; }
        public int ulogaID { get; set; }
        public bool Zaposlen { get; set; }
        public string Email { get; set; }
        public Nullable<int> cijenaID { get; set; }
    
        public virtual Cijena_rada Cijena_rada { get; set; }
        public virtual ICollection<Pocetak_ZavrĹˇetak_rada> Pocetak_ZavrĹˇetak_rada { get; set; }
        public virtual ICollection<Placa> Placa { get; set; }
        public virtual ICollection<Radno_vrijeme> Radno_vrijeme { get; set; }
        public virtual Uloga Uloga { get; set; }
    }
}
