//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBP_Projekt_Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class postgresEntities : DbContext
    {
        public postgresEntities()
            : base("name=postgresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cijena_rada> Cijena_rada { get; set; }
        public DbSet<Korisnik> Korisnik { get; set; }
        public DbSet<Logs> Logs { get; set; }
        public DbSet<Placa> Placa { get; set; }
        public DbSet<Pocetak_ZavrĹˇetak_rada> Pocetak_ZavrĹˇetak_rada { get; set; }
        public DbSet<Radno_vrijeme> Radno_vrijeme { get; set; }
        public DbSet<Uloga> Uloga { get; set; }
    }
}
