//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBP_Projekt_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pocetak_ZavrĹˇetak_rada
    {
        public int pozaRadaID { get; set; }
        public System.DateTime Datum_pocetka { get; set; }
        public Nullable<System.DateTime> Datum_zavrĹˇetka { get; set; }
        public int korisnikID { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
