//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBP_Projekt_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radno_vrijeme
    {
        public int radnoVrijemeID { get; set; }
        public int korisnikID { get; set; }
        public System.TimeSpan Pocetak_rada { get; set; }
        public Nullable<System.TimeSpan> Trajanje_rada { get; set; }
        public System.TimeSpan ZavrĹˇetak_rada { get; set; }
        public Nullable<System.DateTime> Datum_rada { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
