//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBP_Projekt_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uloga
    {
        public Uloga()
        {
            this.Korisnik = new HashSet<Korisnik>();
        }
    
        public int ulogaID { get; set; }
        public string Ime { get; set; }
    
        public virtual ICollection<Korisnik> Korisnik { get; set; }
    }
}
